spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host : redis-13975.c290.ap-northeast-1-2.ec2.redns.redis-cloud.com
      port : 13975
      password: 0Ht4Nkplqe1MXVpu1ygO9ibNNg6B5wMU

  mail:
    host: smtp.gmail.com
    port: 587
    username: unityphj@gmail.com
    password: jvje hxda azzy ooba
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com


  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.psvxzenvipnnptybyojf
    password: nmA9Cute1XQAxmXn


auth:
  jwt:
    issuer: team.HJP.com
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
